### ISSUE TITLE
PrePatch"1x ...nfig-3.0/AceConfigDialog-3.0-81/AceConfigDialog-3.0.lua:2014: attempt to call global 'InterfaceOptions_AddCategory' (a nil value) 

### ISSUE THREAD

**Issue by Tovrin** [N6REJ/Bears_Audio_Switcher#41]
1x ...nfig-3.0/AceConfigDialog-3.0-81/AceConfigDialog-3.0.lua:2014: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Bears_Audio_Switcher/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-81/AceConfigDialog-3.0.lua"]:2014: in function `AddToBlizOptions'
[string "@Bears_Audio_Switcher/core.lua"]:25: in function <Bears_Audio_Switcher/core.lua:17>
[string "=[C]"]: ?
[string "@Bears_Audio_Switcher/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...rs_Audio_Switcher/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Bears_Audio_Switcher/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Bears_Audio_Switcher/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:623: in function <...rs_Audio_Switcher/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals:
self = <table> {
 tooltip = AceConfigDialogTooltip {
 }
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
appName = "BearsSwitcher_Options"
name = "Bears Audio Switcher"
parent = nil
BlizOptions = <table> {
 BearsSwitcher_Options = <table> {
 }
}
key = "BearsSwitcher_Options"
group = <table> {
 type = "BlizOptionsGroup"
 AceGUIWidgetVersion = 22
 base = <table> {
 }
 events = <table> {
 }
 userdata = <table> {
 }
 children = <table> {
 }
 label = FontString {
 }
 frame = Frame {
 }
 content = Frame {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 obj = <table> {
 }
 name = "Bears Audio Switcher"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
AceConfigDialog = <table> {
 tooltip = AceConfigDialogTooltip {
 }
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
gui = <table> {
 objPools = <table> {
 }
 WidgetBase = <table> {
 }
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 tooltip = AceGUITooltip {
 }
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 WidgetContainerBase = <table> {
 }

**Comment by N6REJ** [comment]
I'll be looking at this this week

**Comment by N6REJ** [comment]
fixed in https://github.com/N6REJ/Bears_Audio_Switcher/releases/tag/2024.8.4.17
